# Uncomment the next line to define a global platform for your project
platform :ios, '11'

target 'ImagePickAndClip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImagePickAndClip
pod 'AddRemoteTest', '~> 0.0.5'
  target 'ImagePickAndClipTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImagePickAndClipUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
